name: Create and publish a package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - run: sudo npm run build

    - name: Upload dist folder artifacts
      uses: actions/upload-artifact@v2
      with:
          name: dist
          path: "dist/*"

  package:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Download dist folder artifacts
        uses: actions/download-artifact@v2
        with:
            name: dist
            path: ./dist

      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"

  publish:
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'banou26'
    steps:
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
          name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: "@banou26"
    - run: echo "registry=https://npm.pkg.github.com/@banou26" >> .npmrc
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
